# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Streaming_Response_data_delta
Container for the content of the streamed response.

    StreamingResponseDataDelta(;
        content=nothing,
    )

    - content::String : The content of the streamed response.
"""
Base.@kwdef mutable struct StreamingResponseDataDelta <: OpenAPI.APIModel
    content::Union{Nothing, String} = nothing

    function StreamingResponseDataDelta(content, )
        o = new(content, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type StreamingResponseDataDelta

const _property_types_StreamingResponseDataDelta = Dict{Symbol,String}(Symbol("content")=>"String", )
OpenAPI.property_type(::Type{ StreamingResponseDataDelta }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StreamingResponseDataDelta[name]))}

function OpenAPI.check_required(o::StreamingResponseDataDelta)
    true
end

function OpenAPI.validate_properties(o::StreamingResponseDataDelta)
    OpenAPI.validate_property(StreamingResponseDataDelta, Symbol("content"), o.content)
end

function OpenAPI.validate_property(::Type{ StreamingResponseDataDelta }, name::Symbol, val)

end
