# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module APIClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1.0.0"

include("modelincludes.jl")

include("apis/api_DefaultApi.jl")

# export models
export InferenceRequest
export Message
export InferenceRequestResponseFormat
export InferenceRequestStreamOptions
export InferenceRequestToolsInner
export Function_Params
export InferenceResponse
export ModelData
export NonStreamingResponseChoices
export NonStreamingResponseMessage
export StreamingResponseData
export StreamingResponseDataChoices
export StreamingResponseDataDelta

# export operations
export DefaultApi

end # module APIClient
